### ISSUE TITLE
Screen not working

### ISSUE THREAD

**Issue by pjacob2** [Microsoft/BashOnWindows#1245]
When trying to run `screen` on the Windows Subsystem for Linux upon typing `screen` I get an error message stating:

    Cannot make directory '/var/run/screen': Permission denied

Typing `man screen` I do however get the manual for `screen` so it does appear to be installed.

**Comment by fpqc** [comment]
You have to run it once as root

**Comment by pjacob2** [comment]
That does not solve the problem. Upon typing `sudo screen` I get a message stating `sudo: unable to resolve host LAPTOP-6NV4LA2A`. That message disappears immediately, the terminal is cleared and a message stating `[screen is terminating]` appears. If I subsequently type `screen` I get the same messages.

Closing bash and restarting it typing `screen` produces the initial behaviour described in the original post again.

**Comment by benhillis** [comment]
Could you "sudo rm /etc/hosts", restart bash.exe, and try again?  Looks like that file needs to be regenerated.

**Comment by pjacob2** [comment]
Unfortunately that doesn't seem to change the behaviour.

**Comment by fpqc** [comment]
@pjacob2 Are you on the insider build or 14393.  I don't think this worked yet on 14393.

**Comment by pjacob2** [comment]
I am running Version 1607, OS Build 14393.321.

**Comment by fpqc** [comment]
pjacob yeah you need to upgrade to an insider build, otherwise screen is not yet supported.

**Comment by benhillis** [comment]
This is a duplicate of #774

**Comment by bjoernmartin** [comment]
@benhillis by now I would disagree: #774 fixed issues that prevented screen to work at all. After those were fixed, the issue was closed but left the problem `Cannot make directory '/var/run/screen': Permission denied` unfixed. So it is still (running Windows 10.0.16299.214) required - after each start of e.g. Ubuntu - to run screen once as root to initialized `/var/run/screen`, only then can screen be used as a normal user.

Since this issue was created for this specific problem, I'd suggest to reopen it. Another option would be to reference an issue that deals with the underlying problem (I'm no expert on this but it's discussed in #774 ) so people like me who find this issue know where to look for a solution (or its status).

**Comment by E14** [comment]
By the way, `tmux` works just fine.

**Comment by therealkenc** [comment]
> Cannot make directory '/var/run/screen': Permission denied unfixed

That's #2530

**Comment by WayneD** [comment]
One work-around is to do a "mkdir ~/.screen ; chmod 700 ~/.screen" and then add this to one of your shell's startup files: "export SCREENDIR=/home/USERNAME/.screen" (with the right USERNAME).

**Comment by shaycraft** [comment]
I don't understand why this is closed, as this is still happening.

**Comment by therealkenc** [comment]
Because dupe #2530 is open.

**Comment by ta946** [comment]
[Cannot make directory '/var/run/screen': Permission denied](https://bugs.launchpad.net/ubuntu/+source/screen/+bug/574773)

Quoting the work around posted in the link

> On a freshly booted server install:
>$ screen -ls
>Cannot make directory '/var/run/screen': Permission denied
>
>This can be fixed with:
>$ sudo /etc/init.d/screen-cleanup start
>
>I believe this is because
>/etc/rcS.d/S70screen-cleanup is running via upstart much earlier than it expects to have run, and is failing to correctly clean up that directory.

i added "sudo /etc/init.d/screen-cleanup start" to ~/.bash_profile and that seemed to do the trick

**Comment by philiaagape** [comment]
I like WayneD's solution since it doesn't mess with the system's /run directory or the weird permission problems that screen-cleanup fixes. here's what I put in my .bashrc (a more generic solution that you can copy-pasta):

export SCREENDIR=$HOME/.screen
[ -d $SCREENDIR ] || mkdir -p -m 700 $SCREENDIR

**Comment by jayagami** [comment]
Same problem

I run screen with `sudo`
then `chmod 777 /run/screen`

Seems worked.

**Comment by phdye** [comment]
> Same
> Looks WSL file permission was damaged after I copy some files from windows dir directly.
> 
> I run screen with `sudo`
> then `chmod 777 /run/screen/`
> 
> Seems worked.

You should make that sticky:   chmod 01777 /run/screen

**Comment by AhmetOZER** [comment]
I applied permission to /run/screen folder but every restart requires this fix.
So I change the SCREENDIR to home folder.
To fix for all users at WSL run below comamnd.
```bash
echo 'export SCREENDIR="$HOME/.screen"'
```
if you start screen outside of bash like command line or scheduled task run with environment variables.

```cmd
C:\Users\ahmet>bash -c 'SCREENDIR="$HOME/.screen" screen'
```

**Comment by Sayeed096** [comment]
> I applied permission to /run/screen folder but every restart requires this fix.
> So I change the SCREENDIR to home folder.
> To fix for all users at WSL run below command.
> 
> ```shell
> echo 'export SCREENDIR="$HOME/.screen"'
> ```
> 
> if you start screen outside of bash like command line or scheduled task run with environment variables.
> 
> ```batchfile
> C:\Users\ahmet>bash -c 'SCREENDIR=$HOME/.screen screen'
> ```

Excellent solution I think. I add that command in my **.bashrc** file.

**Comment by brookst** [comment]
Another method is to use the `screen-cleanup` service on boot. WSL supports executing commands on VM boot via the `/etc/wsl.conf` file, like so:

    [boot]
    command="service screen-cleanup start"
