### ISSUE TITLE
python bugs (missing /dev/shm)

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/BashOnWindows#135]
(Also posted at https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13333764-python-bugs since I have no idea which feedback channel to use)

The following python code doesn't work, since /dev/shm is unavailable on Ubuntu on Windows: 
from multiprocessing import Lock 
a = Lock()

I'm getting Errno 38 not implemented

**Comment by patryk9200** [comment]
Same issue as reported here: #16

**Comment by stehufntdev** [comment]
Thanks for reporting the issue. We recently added tmpfs mounts for run (e.g. /run, /run/lock, /run/user, and /run/shm) with permissions that match native Ubuntu. This change should be out for insiders soon.

Locally I was able to confirm the issue above was resolved after the fix.

**Comment by trondhindenes** [comment]
Thanks @stehufntdev  - my goal was to run Ansible under WSL, and this was the first snag. There's a growing community of people using Ansible for Windows management, and having Ansible working under WSL would give is a tremendous productivity boost. Testing it is as easy as git clone + source + execute (http://docs.ansible.com/ansible/intro_installation.html#running-from-source) so if you guys are operating with some kind of "compatability list", a lot of enthusiastic decs would appreciate it if Ansible was added to it.

**Comment by stehufntdev** [comment]
Appreciate the additional details, https://github.com/Microsoft/BashOnWindows/issues/115, was also for Ansible.  With these changes I can run the binary to print the version but there may be other snags as you mentioned.

To get Ansible on our priority list can you add it to our UserVoice [https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash](url) page?  Thanks again for trying out WSL!

**Comment by trondhindenes** [comment]
fyi, the problem remains on the build that was released today.

**Comment by stehufntdev** [comment]
Yes, unfortunately that is expected since the fix didn't make the cutoff for the insider build.  We published the release notes for the build the most recent insider build here - https://msdn.microsoft.com/en-us/commandline/wsl/release_notes.

**Comment by tksarah** [comment]
I tried this combination again with Build 14342.
I looked good working.

**Comment by stehufntdev** [comment]
Great to hear, thanks for the confirmation!

**Comment by trondhindenes** [comment]
I agree, closing the issue. And thanks!

**Comment by fehrin** [comment]
With the python snippet at the very top of this issue i see no error but by simply starting gvim
(gvim:2262): Gdk-WARNING **: shmget failed: error 38 (Function not implemented)
is shown
What could be wrong here?

**Comment by fehrin** [comment]
It seems only Posix shared memory is supported while shmget is System V.

**Comment by sunilmut** [comment]
@fehrin - Thanks for trying out WSL and providing feedback! Unfortunately, `shmget` syscall is currently not implemented in WSL. Please use the [user voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page to provide feedback so that we can prioritize the scenario in future.
