### ISSUE TITLE
Error 0x80070002 in unelevated prompt when there are unsupported volumes mounted.

### ISSUE THREAD

**Issue by dsmaher** [Microsoft/BashOnWindows#1977]
**Your Windows build number:**
10.0.16179

**What you're doing and what's happening:**
Running Bash in an unelevated prompt (for example, within Visual Studio Code), with [Keybase](https://keybase.io) installed.  Keybase mounts a `K:` volume with their own `KBFS` volume type, which appears to be FUSE based.

When I launch `bash` with an unelevated prompt, it terminates immediately with:
```
Error: 0x8007002
```

However, if I run it elevated as Administrator, the `bash` prompt runs normally, and `/mnt/k` exists, but is empty and not usable.

After uninstalling Keybase, `bash` runs normally in both unelevated and elevated modes.

It _might_ be important to note, that there are no issues with Keybase installed on a machine prior to build 16176, 

**What's wrong / what should be happening instead:**
`bash` should still run in unelevated mode regardless of any unsupported mounted volumes.

**Comment by benhillis** [comment]
Thanks for reporting! Looks like the same issue as #1933.  We have fixed this internally and it should be in an Insider build in a couple of weeks.

**Comment by jhit** [comment]
Just for reference and if someone is searching for this error like me. 
I have [boxcryptor classic](https://support.boxcryptor.com/display/DOCDE/Boxcryptor+Classic+Download+und+FAQ) installed which mounts a drive to access a encfs encrypted directory on a real drive.
This mount type also causes the error

Microsoft Windows [Version 10.0.16179]

**Comment by kielby** [comment]
Same issue as jhit, thanks for the heads up.

Any hint as to which insider preview build # will have the fix?

**Comment by jhit** [comment]
Still not fixed on Insider Build [Version 10.0.16188.1000] 😢

**Comment by kielby** [comment]
Looks like it is now fixed in 16193.1001.

**Comment by dsmaher** [comment]
Confirmed fixed in 16193.
