### ISSUE TITLE
Failed to initialize instances shared memory: "QSharedMemory::attach (shmctl): permission denied"

### ISSUE THREAD

**Issue by n3rd4i** [Microsoft/BashOnWindows#2068]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
1. I've installed ubuntu desktop from this [tutorial](https://github.com/microsoft/bashonwindows/issues/637), it works nice
2. I've installed qtcreator, IDE which supports bare metal development
3. Just starting [QT IDE](https://www.qt.io/ide/)
Note: direct link to used [QT IDE](http://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-linux-x64-5.8.0.run)

* What's wrong / what should be happening instead:
The QT creator works BUT I expect no warning for accessing shared memory.
Based on the following [comments](https://github.com/Microsoft/BashOnWindows/issues/61#issuecomment-272768316), `shmctl` is supported.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
`Failed to initialize instances shared memory:  "QSharedMemory::attach (shmctl): permission denied"
[strace.out.txt.6342.txt](https://github.com/Microsoft/BashOnWindows/files/980812/strace.out.txt.6342.txt)

`

Any help on this issue will be appreciated.

**Comment by benhillis** [comment]
@n3rd4i - I'll take a look at this, looks like the permissions check for the shmctl command might be too strict:
```
shmget(0xe0025764, 0, 0600)             = 0
shmat(0, NULL, 0)                       = 0x7f96cf29e000
shmctl(0, IPC_STAT, 0x7fffebcdcf70)     = -1 EACCES (Permission denied)
```

**Comment by benhillis** [comment]
@n3rd4i - Could you go into a bit more detail with your repro steps, specifically the commands used to install Ubuntu Desktop and to install and launch the QT IDE?  I believe I have a fix for the issue but I'm having trouble setting up your repro.

**Comment by n3rd4i** [comment]
@benhillis I'm sorry, by mistake link was wrong, I've edited the links from the original problem post.
1. It seems the first link was somehow copied wrong, the tutorial page was different. 
2. I've added a new link to the exact version of the QT 5.8

I will post more details in next comment.

**Comment by n3rd4i** [comment]
This is the complete flow followed by me to obtain this error message:

## A. installation of Ubuntu desktop:
1. [LINUX] install ubuntu desktop dependencies
  `sudo apt install ubuntu-desktop unity compizconfig-settings-manager -y`
2. [WINDOWS] install the XServer:
  `https://sourceforge.net/projects/vcxsrv/files/vcxsrv/1.19.2.0/`
3. [WINDOWS] append XServer bin path to PATH permanently
  `System Properties >> Environment Variables >> PATH >> EDIT >> NEW >> <VCXSRV_BIN_PATH>`
4. [LINUX] assuming desktop dependencies are installed now, start [WIN] XServer from linux bash:
  `vcxsrv.exe -multiwindow -clipboard -wgl &`
  Note: this is the multiwindows mode, for setting-up `ccsm`
5. [LINUX] run ccsm:
 `ccsm`
6. [LINUX] kill the process from linux bash, of [WIN] XServer
 `taskkill.exe /IM vcxsrv.exe /F`
7. [LINUX] start [WIN] XServer from linux bash, this time as full screen: 
 `vcxsrv.exe -clipboard -wgl -dpi auto &`
8. [OPTIONAL] [WINDOWS] rescale the XServer screen if required/preferred ( from default ):

## B. Starting Ubuntu Desktop
1. [LINUX] start Ubuntu Desktop:
 `compiz &`

## C. Installing QT 5.8:
1. [LINUX] download the package:
 `wget http://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-linux-x64-5.8.0.run`
2. [LINUX] make it executable:
 `chmod +x qt-opensource-linux-x64-5.8.0.run`
3. [LINUX] start the installation wizard:
 `./qt-opensource-linux-x64-5.8.0.run &`
4. [OPTIONAL] [LINUX DESKTOP] 
  `Note: Don't forget, check the tickbox to start the QT Creator, after installation`
5. [OPTIONAL] [LINUX DESKTOP] preserve the icon/shortcut to QT Creator for later use
 `Right click on icon on new instance of QT Creator, "Lock to Launcher"`

## D. Detecting the problem:
1. [LINUX DESKTOP] exit QT Creator if open:
 `No instance of QT Creator is running`
2. [LINUX BASH] clear the bash for future messages
 `clear`
3. [LINUX DESKTOP] start QT Creator normally:
 `click on the created icon`
4. The error message should be there in the bash messages.
  `Failed to initialize instances shared memory:  "QSharedMemory::attach (shmctl): permission denied"`

**Comment by benhillis** [comment]
Thank you that's very helpful. I was swamped with //build/ conference stuff this week so I'll give this a shot with my fix.

**Comment by benhillis** [comment]
I am having a hard time setting this up, I think it's likely because I am using a virtual machine that does not support OpenGL graphics.  Question, if you run qtcrator as root do you still see the same error?

**Comment by n3rd4i** [comment]
If I run: `sudo qtcreator &`
I don't have the same error.

**Comment by n3rd4i** [comment]
### The following are my ccsm settings

![accesibility](https://cloud.githubusercontent.com/assets/7346660/26170410/9fad95d0-3b41-11e7-991b-44087c3b9107.PNG)
![desktop](https://cloud.githubusercontent.com/assets/7346660/26170404/9f9fe57a-3b41-11e7-836f-824041230f4e.PNG)
![effects](https://cloud.githubusercontent.com/assets/7346660/26170409/9fac52d8-3b41-11e7-9bb8-e624444f3429.PNG)
![general settings](https://cloud.githubusercontent.com/assets/7346660/26170408/9fa8136c-3b41-11e7-8e85-c39246765a52.PNG)
![image loading](https://cloud.githubusercontent.com/assets/7346660/26170406/9fa55a5a-3b41-11e7-989b-37dd3016a7be.PNG)
![uncategorized](https://cloud.githubusercontent.com/assets/7346660/26170405/9fa15d42-3b41-11e7-93cf-eafde25a3ad7.PNG)
![utility](https://cloud.githubusercontent.com/assets/7346660/26170411/9fc20ea2-3b41-11e7-866c-bc108593d290.PNG)
![window management](https://cloud.githubusercontent.com/assets/7346660/26170412/9fc885c0-3b41-11e7-83a7-42fcddce94e2.PNG)

**Comment by n3rd4i** [comment]
There are 2 possible cases which I found:
1. Open a full desktop view, with the following command, assumed that the above OpenGL is enabled.
`vcxsrv.exe -clipboard -wgl -dpi auto &`
2. Use the workaround described [here](https://bugreports.qt.io/browse/QTBUG-50599?focusedCommentId=303857&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303857)
`qtcreator -noload Welcome -noload QmlDesigner -noload QmlProfiler &`

**Comment by therealkenc** [comment]
@benhillis - Simple repro steps if you are still tracking this: Start [VcXsrv](https://sourceforge.net/projects/vcxsrv/) with XLaunch. Choose multi-window, and then Native opengl _unchecked_ on the "Extra settings page". Then:
```
$ sudo apt install ubuntu-desktop qtcreator
$ export display=localhost:0
$ qtcreator
```
I'm not going to do a snippet for the fail here since you think it's already squashed, but if you guys are starting to entertain graphics apps as test cases, those are the steps. And those are _always_ the steps, whether you are running `xlogo` or `google-chrome-unstable`.

**Comment by benhillis** [comment]
I apologize for the delay, I've submitted a fix for this issue. Look for the fix in a Windows Insider build in a few weeks time.

**Comment by benhillis** [comment]
Fixed in 16237.

**Comment by fehrin** [comment]
Hi, will this fix be in the autumn creators update?

**Comment by therealkenc** [comment]
@fehrin - anything that made it into 16237 should be in Falls.  The Insider Builds are just six months of "Fall Update Pre-Releases". We haven't got any of the _post_ Fall Update pens down stuff yet.

**Comment by shabiel** [comment]
Hello All,

I just got Windows 10 1809 installed TODAY. I was hoping to have had this issue fixed; but apparently it is not fixed:

Error message: %YDB-E-DBFILERR, Error with database file /home/sam/db/VPE/g/mumps.dat,%YDB-I-TEXT, Error with database co
ntrol semctl IPC_STAT1,%SYSTEM-E-ENO13, Permission denied

From strace:
```
$ strace mumps -r ^%GD <<<"" |& grep semctl
semctl(1, 2, SETVAL, 0x2b)              = 0
semctl(2, 2, IPC_STAT, 0x7fffd250bd60)  = -1 EACCES (Permission denied)
semctl(2, 0, IPC_RMID, NULL)            = 0
```

**Comment by therealkenc** [comment]
Dunno what Ben [fixed](https://github.com/Microsoft/WSL/issues/2068#issuecomment-314257299) exactly but whatever it was, it shipped in 16237. Just tried the instant [repro steps](https://github.com/Microsoft/WSL/issues/2068#issuecomment-302897165) and qtcreator lit up nicely. For completeness this was on Ubuntu 18.04 userspace, WSL 18305, and qtcreator 4.5.2 based on Qt 5.9.5 -- but that won't matter. The syscall emulation gap this issue represents was closed a year and a half ago. If you've got CLI repro steps for your fail feel free to spin up a new issue following CONTRIBUTING.md and the template.

**Comment by shabiel** [comment]
Thank you. I will create a new issue.
