### ISSUE TITLE
issues with paste on bash on ubuntu on windows

### ISSUE THREAD

**Issue by alexeyshishkin01** [Microsoft/BashOnWindows#2131]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
'Microsoft Windows [Version 10.0.14393]'

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
'I've installed Bash on Ubuntu on Windows following the
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows
I open 'Notepad' and type 'hello-привет'.
Then I copy typed text and try to paste it onto Ubuntu command line.
If my current keyboard language is English the result of paste command it 'hello-' (i.e. Russian letters are not pasted).
When I switch my keyboard language to Russian and paste it again the result of it is '-привет' (i.e. English letters are not pasted).
You see '-' symbol is pasted in both tests.
The issue doesn't exist when copying to 'cmd.exe' console, i.e. the pasted text is the same as copied - 'hello-привет' regardless of the current keyboard language'

* What's wrong / what should be happening instead:
'Pasted test should be the same as copied text regardless of the current keyboard language'

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
'Nothing of the kind'

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunjoong** [comment]
@alexeyshishkin01 - What if using legacy console? Same problem? If, so... #2049 said there is a issue of cyrillic text  when using new console (it might be default). https://github.com/Microsoft/BashOnWindows/issues/1124#issuecomment-261707397 is a somehow different issue; it looks like font issue.

**Comment by alexeyshishkin01** [comment]
hi, there,  
#2049 is about a bug for typing Cyrillic text - I don't have such issue, I can type Cyrillic.
my issue is with pasting Cyrillic into Bash on Windows.
legacy console is not supported by Bash on Windows (it's not possible to launch Bash on Windows in legacy console)
#1124 - I don't think it's a font issue because when I switch keyboard language from English to Russian the copied test is pasted (even partially)

**Comment by sunjoong** [comment]
@alexeyshishkin01 - Ah... I ment that comment looked like font issue.

BTW, I copied "`hello-привет`" from above and pasted it to `notepad` window, and then coped from notepad window to `bash` console after echo+blank position;
![figure](https://cloud.githubusercontent.com/assets/2748000/26242269/c53955dc-3cc2-11e7-9295-0c60f7845cf3.png)

**Comment by alexeyshishkin01** [comment]
may I ask you to screenshot your console settings?

**Comment by alexeyshishkin01** [comment]
and windows version pls.

**Comment by sunjoong** [comment]
@alexeyshishkin01 - Microsoft Windows [Version 10.0.15063]

Properies of bash console are default settings;
![property](https://cloud.githubusercontent.com/assets/2748000/26243193/f2471d22-3cc5-11e7-8a5f-7f37a2859d0a.png)

**Comment by alexeyshishkin01** [comment]
thanks, your Windows version is 10.0.15063 is different from mine 10.0.14393
and you use the font which is not available for me, may I ask you to temporary switch to 'Lucida Console' font which I use and repeat the 'copy/paste' test?

**Comment by sunjoong** [comment]
@alexeyshishkin01 - In Lucida Console font, it works well.

Hmm... You wrote `hello-привет` string in notepad and copyed it, so that string might be sent this path; notepad -> clipboard (hidden) -> bash console. I guess... it seems to cut unknown ( I don't know what's the exact term so chose the word unknown ) characters depending on keyboard layout setteing. It might be happen between notepad and clipboard or clipboard and bash. I began to think this after reading http://winrus.com/cp_r.htm .

**Comment by alexeyshishkin01** [comment]
I don't think it depends on what you copy the text from: notepad or browser.
Look: in Bash console I can type 'привет', then select it by mouse, copy it to clipboard and try to paste it just near the same first word 'привет'.
If the keyboard layout is Russian it can be pasted, but if it's English - it can't.
Similar situation to English - in Bash type 'hello', copy it and try to paste just right here - with English keyboard layout it can be pasted, with Russian it cannot.
When I say cannot be pasted it means nothing pasted at all, i.e. the cursor position is the same after paste.
The symbol '-' is pasted regardless of English/Russian keyboard layout.
thanks!

**Comment by sunjoong** [comment]
@alexeyshishkin01 - I meant I guessed it might be a unicode string conversion issue, not coppying from notepad or browser; I just mentioned the browser for saying my string might be a unicode string.

I found a windows PowerShell command `Get-Clipboard`; It looks like a command to check the content of windows clipboard. When I copy a string `hello-привет` from web or notepad or bash console or whatever, I could check it as same result on windows PowerShell like this;
```
PS C:\Users\sunjoong> Get-Clipboard
hello-привет
PS C:\Users\sunjoong>
```

If you got different results depending on your keyboard layout, this might not be a simply WSL issue, might be a unicode issue, I think.

**Comment by alexeyshishkin01** [comment]
yes, the result is the same in Get-Clipboard
I have even tried to copy from Windows Character Map (charmap.exe) and paste it to Bash console - the result is the same as with copy/paste from Notepad

**Comment by zadjii-msft** [comment]
@alexeyshishkin01 What font are you using when the characters don't show up in bash? 

Does highlighting the input with the mouse (selecting it) cause the appearance to change? Try selecting past the end of where the text is visible.

Could you post the output of running `chcp` in a `cmd.exe` window?
Also, could you try running `chcp 65001` in a cmd window, then try pasting `hello-привет` in that window?

**Comment by sunjoong** [comment]
@alexeyshishkin01 - Don't panic. @zadjii-msft could help you. BTW, you said "the result is the same in Get-Clipboard". If you mean the same as that it is not depending on keyboard layout, it looks like I was wrong; sorry.

@zadjii-msft - I don't know what font @alexeyshishkin01 use exactly, but @alexeyshishkin01 asked me to test with Lucida Console font; That means it could happen in Lucida Console font.

**Comment by alexeyshishkin01** [comment]
![font](https://cloud.githubusercontent.com/assets/28735514/26266618/ca10b092-3cee-11e7-8143-64b0d70c0dbb.jpg)
I use Lucida Console font

**Comment by alexeyshishkin01** [comment]
![codepage](https://cloud.githubusercontent.com/assets/28735514/26266653/f2566fc4-3cee-11e7-8baf-58f74062e6dc.jpg)
I use 65001 code page

**Comment by alexeyshishkin01** [comment]
let's change the text a bit: now it's '-hello-привет-'
![test01](https://cloud.githubusercontent.com/assets/28735514/26266963/73e9b220-3cf0-11e7-8dc2-34d8b7163ae5.jpg)
since symbol '-' is always pasted you see that depending on keyboard layout part of the text disappears during paste

**Comment by alexeyshishkin01** [comment]
so, I don't believe the issue is with font, because English letters cannot be pasted as well as Russian depending on keyboard layout

**Comment by zadjii-msft** [comment]
Oh my. That looks like a bug to me. 

To help me debug, @alexeyshishkin01 could you repeat those echo statements and keyboard changes in `cmd.exe` too? That'll help me narrow down what the source might be.

In the meantime, I'm filing MSFT:12077421 on our internal work tracker to make sure this gets investigated.

**Comment by alexeyshishkin01** [comment]
![test02](https://cloud.githubusercontent.com/assets/28735514/26267746/73628904-3cf4-11e7-9edc-68a6f74f851a.jpg)
similar test on 'cmd.exe' - no issues at all

**Comment by alexeyshishkin01** [comment]
pls. feel free to ask as many questions as you need concerning the issue. thanks!

**Comment by zadjii-msft** [comment]
👍 Awesome! That means that specifically bash.exe has something to do with this bug.

**Comment by alexeyshishkin01** [comment]
most probably yes, but you are to confirm :-)

**Comment by sunjoong** [comment]
@zadjii-msft - #1056 looks very closely like this issue, but... that labled `fixedinsiderbuilds` and... there was a [comment](https://github.com/Microsoft/BashOnWindows/issues/1056#issuecomment-276896575);
> I confirm, at least on 14986 this issue cannot be reproduced - thus considered fixed.

@alexeyshishkin01 said their version is 14393.

But, you know.... my issue is on 15063.

**Comment by alexeyshishkin01** [comment]
thanks for that, is it possible to have a fix only for that issue instead of upgrading Windows version?
besides how can I update to particular version of Windows? say from my current '14393' to issue-free version '14986' or '15063'?

**Comment by sunjoong** [comment]
@alexeyshishkin01 - 14986 is insiderbuilds version, 14393 is the latest builds of 1607 version (Redstone 1; Anniversary Update), and 15063 is the  latest builds of 1703 version (Redstone 2; Creators Update).

I think.... https://support.microsoft.com/en-us/help/3159635/windows-10-update-assistant may help you to update from Redstone1 to Redston2.

* https://blogs.windows.com/windowsexperience/2017/04/11/how-to-get-the-windows-10-creators-update
* http://www.windowscentral.com/how-get-windows-10-creators-update
* http://www.thewindowsclub.com/windows-10-upgrade-assistant

**Comment by alexeyshishkin01** [comment]
ok, I see, but what about particular fix for the issue? upgrading my current Windows version to insiderbuild one is a move I have to think of and to be prepared to. thanks for understanding.

**Comment by sunjoong** [comment]
@alexeyshishkin01 - As I heard.... updateing WSL is depending on Windows. And... insiderbuilds is not a regular(?) version, but Redstone 2 is standard(?) version.

**Comment by zadjii-msft** [comment]
@alexeyshishkin01 If you're on 14393, I'd definitely recommend upgrading to 15063. That's the next "official" release of Windows, and has a TON of improvements to WSL. 

Furthermore, there's not a mechanism for just getting small single fixes like the one in #1056 without a whole OS upgrade. Unfortunately the WSL components and conhost are just not set up for that kind of patching. 

I can also confirm that this issue repros on 16197, which is an internal daily build, so it's not resolved by #1056, though it's probably related.

**Comment by sunjoong** [comment]
@zadjii-msft - Reproducable on 16197?? Somehow... it sounds strange, I feel. Because....

At https://github.com/Microsoft/BashOnWindows/issues/1056#issuecomment-276697893, @miniksa had said;
> It looks like this issue was resolved internally because no one could reproduce it.
> I just tried it myself against 14393 and 15024 and it doesn't reproduce for me in either case.

That issue had been raised on 14393 but they had said had not been to reproduce against 14393. @ilyaigpetrov had replied to at https://github.com/Microsoft/BashOnWindows/issues/1056#issuecomment-276700789;

> 3. Paste "foo-фи" with a right click of a mouse. (Compose another string for another layouts).
> 4. Depending on the current layout selected either "foo-" (for EN) or "-фи" (for RU) will be pasted.

They had reproduced it with "`foo-фи`" string. When @alexeyshishkin01 raised this issue on 14393, they used the "`hello-привет`" string.

At https://github.com/Microsoft/BashOnWindows/issues/1056#issuecomment-276709710, @miniksa had replied
> I can reproduce it against 14393, the July release. But it has already been resolved in the Insider Previews for the upcoming spring update.

**Comment by alexeyshishkin01** [comment]
ok, I've upgraded to 15063, the issue is gone, but frankly I still don't understand why a small fix couldn't have been provided instead of OS upgrade

**Comment by sunjoong** [comment]
@alexeyshishkin01 - Good for you. I thought this issue was a duplicate of #1056 since two days ago. But... "repros on 16197" could be a REAL issue.

>  I still don't understand why a small fix couldn't have been provided instead of OS upgrade

There are other people who feel same thing like you; #2041.

**Comment by miniksa** [comment]
This issue is confirmed resolved in the Creators Update (15063) so I'll be closing it here.

**Comment by benhillis** [comment]
One remaining issue was resolved in 16257.

**Comment by alexeyshishkin01** [comment]
ok, many thanks waiting for the fix binary
