### ISSUE TITLE
Can't install RVM 

### ISSUE THREAD

**Issue by kaanoo2904** [Microsoft/BashOnWindows#222]
I'm trying to install RVM, and when i try to run

    curl -L https://get.rvm.io | bash -s stable

Bash return sth like this:

    ....
    install: cannot create symlink to 'scripts/install" : invalid argument
    ...
    tar: scripts/functions/requirements/mint: Cannot create symlink to ‘ubuntu’: Invalid argument
    .... 
     (tar: scripts/functions/requirements/mint: Cannot create symlink to + all other linux OS ...
    .....
    tar: bin/rvm-installer: Cannot create symlink to ‘../binscripts/rvm-installer’: Invalid argument
    tar: Exiting with failure status due to previous errors
    Could not extract RVM sources.

It's look like someone got problem with symlink when install NVM here 

https://github.com/creationix/nvm/issues/1054

**Comment by patryk9200** [comment]
@kaanoo2904 This is known issue see: #9
It's fixed in internal builds, more info here: https://github.com/Microsoft/BashOnWindows/issues/9#issuecomment-207904851

**Comment by benhillis** [comment]
Closing this out as it's a duplicate of #9.  Thanks for trying out our stuff and reporting the issue though!

**Comment by benhillis** [comment]
Reopening to discuss further install issues.

**Comment by Dunkirk** [comment]
Now that #9 is fixed, you can install RVM itself, but afterwards, it complains:

`* WARNING: you are missing '/dev/fd' it is important for shell scripting used by RVM,
You can fix it on most linux systems with:
ln -sf /proc/self/fd /dev/fd`

Indeed, when you then try to install a version of Ruby, you get lots of references to the problem:

`root@ENTERPRISE:~# rvm install 2.2.3
ruby-2.2.3 - #removing src/ruby-2.2.3..
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.2.3.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
df: Warning: cannot read table of mounted file systems: No such file or directory
ruby-2.2.3 - #configure
ruby-2.2.3 - #download
ruby-2.2.3 - #validate archive
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
The downloaded package for https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.2.3.tar.bz2,
Does not contains single 'bin/ruby' or 'ruby-2.2.3',
Only '' were found instead.
Mounting remote ruby failed with status 4, trying to compile.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for ubuntu.
grep: write error: Broken pipe
sort: fflush failed: standard output: Broken pipe
sort: write error
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.2.3, this may take a while depending on your cpu(s)...
ruby-2.2.3 - #downloading ruby-2.2.3, this may take a while depending on your connection...
ruby-2.2.3 - #extracting ruby-2.2.3 to /usr/local/rvm/src/ruby-2.2.3....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
bash: echo: write error: Broken pipe
ruby-2.2.3 - #configuring.........................................................
ruby-2.2.3 - #post-configuration..
ruby-2.2.3 - #compiling...............................................................................
ruby-2.2.3 - #installing..........................
Error running '__rvm_make install',
showing last 15 lines of /usr/local/rvm/log/1461353546_ruby-2.2.3/install.log
make[2]: Entering directory `/usr/local/rvm/src/ruby-2.2.3/ext/win32ole'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/local/rvm/src/ruby-2.2.3/ext/win32ole'
make[2]: Entering directory `/usr/local/rvm/src/ruby-2.2.3/ext/zlib'
make[2]: Leaving directory `/usr/local/rvm/src/ruby-2.2.3/ext/zlib'
make[2]: Entering directory `/usr/local/rvm/src/ruby-2.2.3'
make[2]: `ruby' is up to date.
make[2]: Leaving directory `/usr/local/rvm/src/ruby-2.2.3'
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.3'
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
./tool/runruby.rb:70: warning: Insecure world writable dir /usr/local/rvm/bin in PATH, mode 042777
./tool/runruby.rb:99:in `exec': Cannot allocate memory - ./ruby (Errno::ENOMEM)
        from ./tool/runruby.rb:99:in `<main>'
make: *** [do-install-nodoc] Error 1
++ return 2
There has been an error while running make install. Halting the installation.`

**Comment by dreyks** [comment]
are you using an internal build? cause i've just updated to 14328 and i'm still being hold back by symlink issue

**Comment by hfaran** [comment]
I use a non-root user on my system as well and got the same as @dreyks on 14328.

**Comment by russalex** [comment]
Wanted to give an update here since this is a topic a lot of people care about.  Wrote this up in #50, but adding it here.

RVM install failed for me on 14328. For fun, I tried it on an internal build and seeing:

- Install worked but with a non-critical error
- rvm install 1.9.2 displayed more non-critical errors
- rvm use 1.9.2 required me to launch bash with "bash -c "/bin/bash --login"

Output is:

> russ@RUSSALEX-DESK:~$ rvm use 1.9.2
> Using /home/russ/.rvm/gems/ruby-1.9.2-p330
> russ@RUSSALEX-DESK:~$ ruby -version
> ruby 1.9.2p330 (2014-08-07 revision 47094) [x86_64-linux]
> -e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)

Punchline is: this build is much better than the last, but good things are still on the way.

**Comment by dreyks** [comment]
Since 14332 has landed, I successfully managed to install rvm as a non-root user but the ruby installation still fails.
```console
$ rvm install 2.3.0
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.0.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
df: Warning: cannot read table of mounted file systems: No such file or directory
ruby-2.3.0 - #configure
ruby-2.3.0 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25.1M  100 25.1M    0     0  2976k      0  0:00:08  0:00:08 --:--:-- 5271k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.0 - #validate archive
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
The downloaded package for https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.0.tar.bz2,
Does not contains single 'bin/ruby' or 'ruby-2.3.0',
Only '' were found instead.
Mounting remote ruby failed with status 4, trying to compile.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/dreyk/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
sort: fflush failed: standard output: Broken pipe
sort: write error
grep: write error: Broken pipe
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.5M  100 13.5M    0     0  2557k      0  0:00:05  0:00:05 --:--:-- 3575k
ruby-2.3.0 - #extracting ruby-2.3.0 to /home/dreyk/.rvm/src/ruby-2.3.0....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
ruby-2.3.0 - #configuring..........................................................
ruby-2.3.0 - #post-configuration..
ruby-2.3.0 - #compiling....................................
ruby-2.3.0 - #installing......
Error running '__rvm_make install',
showing last 15 lines of /home/dreyk/.rvm/log/1461880464_ruby-2.3.0/install.log
make[2]: Entering directory `/home/dreyk/.rvm/src/ruby-2.3.0/ext/io/nonblock'
rm -f ../../../.ext/x86_64-linux/io/nonblock.so ../../../.ext/.timestamp/.RUBYARCHDIR.-.io.time
rmdir --ignore-fail-on-non-empty -p ../../../.ext/x86_64-linux/io 2> /dev/null || true
rm -f
rm -f ../../../.ext/x86_64-linux/io/nonblock.so  *.o  *.bak mkmf.log .*.time
rm -f Makefile extconf.h conftest.* mkmf.log
rm -f core ruby *~
rmdir --ignore-fail-on-non-empty -p  2> /dev/null || true
make[2]: Leaving directory `/home/dreyk/.rvm/src/ruby-2.3.0/ext/io/nonblock'
make[1]: Leaving directory `/home/dreyk/.rvm/src/ruby-2.3.0'
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
./ruby is not found.
Try `make' first, then `make test', please.
make: *** [do-install-nodoc] Error 1
++ return 2
There has been an error while running make install. Halting the installation.
```

**Comment by PurityControl** [comment]
Have you tried extracting the ruby package manually and running `make` then `make test` ?

**Comment by dreyks** [comment]
Yup. Everything seems ok?
```console
$ make test
        CC = gcc
        LD = ld
        LDSHARED = gcc -shared
        CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -std=iso9899:1999  -fPIC
        XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT
        CPPFLAGS =   -I. -I.ext/include/x86_64-linux -I./include -I.
        DLDFLAGS = -Wl,-soname,libruby.so.2.3  -fstack-protector
        SOLIBS = -lpthread -lgmp -ldl -lcrypt -lm
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
linking ruby

test succeeded
PASS all 1010 tests
exec ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./bootstraptest/runner.rb" --ruby="ruby --disable-gems"   ./KNOWNBUGS.rb
2016-04-29 17:25:45 +0000
Driver is ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Target is ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

KNOWNBUGS.rb  PASS 0
No tests, no problem
```

**Comment by jvilleneuve** [comment]
I'd like to +1 dreyks  comment above. I have the same results, using RVM and building rbenv as per http://qiita.com/chimame/items/3787a59eca1005b89eac (sorry about the Japanese, just follow the terminal commands as they are self explanatory).

Regardless of the path I take, the same make error persists

**Comment by benhillis** [comment]
I verified this morning that I was able to user RVM to install ruby 2.3.0 without issues on our internal build.  I know that RVM was using some clone support that we lit up recently so it looks like this is resolved.

**Comment by zerocool4u2** [comment]
Great! really appreciate! regards.

**Comment by jvilleneuve** [comment]
@benhillis Can you also verify that you can build ruby via rbenv?

**Comment by PurityControl** [comment]
@benhills do you know when the next update is likely to be pushed out with this fix in it?

**Comment by hfaran** [comment]
@PurityControl @benhillis has mentioned before that his team has no influence on when new flights are released to the fast ring. If you're on the fast ring, just be on the watch for an update and it will likely be in that.

**Comment by PurityControl** [comment]
@hfaran many thanks

**Comment by itsmevasanth** [comment]
I'm trying to install ruby 2.2.4 from the package. Still I get 'Unable to allocate memory' error.
Am I missing something
`root@DESKTOP-V6SLQKF:/usr/local/rvm/src/ruby-2.2.4# make test
        CC = gcc
        LD = ld
        LDSHARED = gcc -shared
        CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -std=iso9899:1999
        XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -fPIE
        CPPFLAGS =   -I. -I.ext/include/x86_64-linux -I./include -I.
        DLDFLAGS = -fstack-protector -pie
        SOLIBS = -lgmp
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
linking ruby
making enc
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Nothing to be done for `enc'.
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
making srcs under enc
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Nothing to be done for `srcs'.
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
generating transdb.h
transdb.h unchanged
making trans
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Nothing to be done for `./enc/trans'.
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
making encs
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
generating makefile exts.mk
Failed to configure -test-/win32/console. It will not be installed.
Failed to configure -test-/win32/dln. It will not be installed.
Failed to configure -test-/win32/dln/empty. It will not be installed.
Failed to configure -test-/win32/fd_setsize. It will not be installed.
configuring mathn/rational
Failed to configure tk. It will not be installed.
Failed to configure tk/tkutil. It will not be installed.
Failed to configure win32. It will not be installed.
Failed to configure win32ole. It will not be installed.
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make -C ext/mathn/rational -w V= realclean
make[2]: Entering directory `/usr/local/rvm/src/ruby-2.2.4/ext/mathn/rational'
rm -f ../../../.ext/x86_64-linux/mathn/rational.so
rmdir --ignore-fail-on-non-empty -p ../../../.ext/x86_64-linux/mathn 2> /dev/null || true
rm -f
rm -f ../../../.ext/x86_64-linux/mathn/rational.so  *.o  *.bak mkmf.log .*.time
rm -f Makefile extconf.h conftest.* mkmf.log
rm -f core ruby *~
rmdir --ignore-fail-on-non-empty -p  2> /dev/null || true
make[2]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4/ext/mathn/rational'
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
Generating RDoc documentation
./tool/runruby.rb:70: warning: Insecure world writable dir /usr/local/rvm/bin in PATH, mode 042777
./tool/runruby.rb:100:in `exec': Cannot allocate memory - ./ruby (Errno::ENOMEM)
        from ./tool/runruby.rb:100:in `<main>'
make: *** [rdoc] Error 1`

**Comment by itsmevasanth** [comment]
I'm currently on build 14342 which is supposed to fix the memory allocation issue. Am I missing something?

Trying to install ruby 2.2.4

`root@DESKTOP-V6SLQKF:/usr/local/rvm/src/ruby-2.2.4# make test
        CC = gcc
        LD = ld
        LDSHARED = gcc -shared
        CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -std=iso9899:1999
        XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -fPIE
        CPPFLAGS =   -I. -I.ext/include/x86_64-linux -I./include -I.
        DLDFLAGS = -fstack-protector -pie
        SOLIBS = -lgmp
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
making enc
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Nothing to be done for `enc'.
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
making srcs under enc
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Nothing to be done for `srcs'.
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
generating transdb.h
transdb.h unchanged
making trans
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Nothing to be done for `./enc/trans'.
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
making encs
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
generating makefile exts.mk
Failed to configure -test-/win32/console. It will not be installed.
Failed to configure -test-/win32/dln. It will not be installed.
Failed to configure -test-/win32/dln/empty. It will not be installed.
Failed to configure -test-/win32/fd_setsize. It will not be installed.
configuring mathn/rational
Failed to configure tk. It will not be installed.
Failed to configure tk/tkutil. It will not be installed.
Failed to configure win32. It will not be installed.
Failed to configure win32ole. It will not be installed.
make[1]: Entering directory `/usr/local/rvm/src/ruby-2.2.4'
make -C ext/mathn/rational -w V= realclean
make[2]: Entering directory `/usr/local/rvm/src/ruby-2.2.4/ext/mathn/rational'
rm -f ../../../.ext/x86_64-linux/mathn/rational.so
rmdir --ignore-fail-on-non-empty -p ../../../.ext/x86_64-linux/mathn 2> /dev/null || true
rm -f
rm -f ../../../.ext/x86_64-linux/mathn/rational.so  *.o  *.bak mkmf.log .*.time
rm -f Makefile extconf.h conftest.* mkmf.log
rm -f core ruby *~
rmdir --ignore-fail-on-non-empty -p  2> /dev/null || true
make[2]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4/ext/mathn/rational'
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.4'
Generating RDoc documentation
./tool/runruby.rb:70: warning: Insecure world writable dir /usr/local/rvm/gems in PATH, mode 042777
./tool/runruby.rb:100:in `exec': Cannot allocate memory - ./ruby (Errno::ENOMEM)
        from ./tool/runruby.rb:100:in `<main>'
make: *** [rdoc] Error 1`

**Comment by Austin-Qu** [comment]
I tried to install ruby-2.2.3 with RVM. Still failed.

Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.2.3.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
df: Warning: cannot read table of mounted file systems: No such file or directory
ruby-2.2.3 - #configure
ruby-2.2.3 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 22.9M  100 22.9M    0     0   101k      0  0:03:51  0:03:51 --:--:-- 85183
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.2.3 - #validate archive
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
The downloaded package for https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.2.3.tar.bz2,
Does not contains single 'bin/ruby' or 'ruby-2.2.3',
Only '' were found instead.
Mounting remote ruby failed with status 4, trying to compile.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for ubuntu.
Requirements installation successful.
sort: fflush failed: standard output: Broken pipe
sort: write error
grep: write error: Broken pipe
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.2.3, this may take a while depending on your cpu(s)...
ruby-2.2.3 - #downloading ruby-2.2.3, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0  1359k      0  0:00:09  0:00:09 --:--:-- 1620k
ruby-2.2.3 - #extracting ruby-2.2.3 to /usr/local/rvm/src/ruby-2.2.3....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
bash: echo: write error: Broken pipe
ruby-2.2.3 - #configuring.........................................................
ruby-2.2.3 - #post-configuration..
ruby-2.2.3 - #compiling...................................
ruby-2.2.3 - #installing.......
Error running '__rvm_make install',
showing last 15 lines of /usr/local/rvm/log/1463064119_ruby-2.2.3/install.log
make[2]: Entering directory `/usr/local/rvm/src/ruby-2.2.3/ext/mathn/rational'
rm -f ../../../.ext/x86_64-linux/mathn/rational.so
rmdir --ignore-fail-on-non-empty -p ../../../.ext/x86_64-linux/mathn 2> /dev/null || true
rm -f
rm -f ../../../.ext/x86_64-linux/mathn/rational.so  *.o  *.bak mkmf.log .*.time
rm -f Makefile extconf.h conftest.* mkmf.log
rm -f core ruby *~
rmdir --ignore-fail-on-non-empty -p  2> /dev/null || true
make[2]: Leaving directory `/usr/local/rvm/src/ruby-2.2.3/ext/mathn/rational'
make[1]: Leaving directory `/usr/local/rvm/src/ruby-2.2.3'
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
./ruby is not found.
Try `make' first, then `make test', please.
make: *** [do-install-nodoc] Error 1
++ return 2
There has been an error while running make install. Halting the installation.

**Comment by dev-seahouse** [comment]
Same error, but can install ruby without using rvm without issue

$ sudo apt-add-repository ppa:brightbox/ruby-ng
$ sudo apt-get update
sudo apt-get install ruby2.3 ruby2.3-dev

**Comment by natanlim** [comment]
@dev-seahouse your Ruby on Rails is working without problems?

**Comment by TheRealKingS** [comment]
Tried to install rvm on build 14342 with german language pack.

This is the error:
` kings@STEPHANLAPTOP  ~  \curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
gpg: Signature made Tue 29 Mar 2016 01:49:47 PM UTC using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/kings/.rvm/archives/rvm-1.27.0.tgz'

Upgrading the RVM installation in /home/kings/.rvm/
cat: /dev/fd/63: No such file or directory
    RVM PATH line found in /home/kings/.mkshrc /home/kings/.profile /home/kings/.bashrc.
    RVM PATH line not found for Zsh, rerun this command with '--auto-dotfiles' flag to fix it.
    RVM sourcing line found in /home/kings/.profile /home/kings/.bash_profile /home/kings/.zlogin.
Upgrade of RVM in /home/kings/.rvm/ is complete.

# kings,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

/home/kings/.zshrc:56:  export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/kings/.rvm/bin:/home/kings/.rvm/bin"

  * WARNING: Above files contains `PATH=` with no `$PATH` inside, this can break RVM,
    for details check https://github.com/rvm/rvm/issues/1351#issuecomment-10939525
    to avoid this warning append #PATH.

  * No new notes to display.

rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.3.0 - #removing src/ruby-2.3.0..
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.0.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
df: Warning: cannot read table of mounted file systems: No such file or directory
ruby-2.3.0 - #configure
ruby-2.3.0 - #download
ruby-2.3.0 - #validate archive
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
The downloaded package for https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.0.tar.bz2,
Does not contains single 'bin/ruby' or 'ruby-2.3.0',
Only '' were found instead.
Mounting remote ruby failed with status 4, trying to compile.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for ubuntu.
Requirements installation successful.
Found user configured '-j' flag in 'rvm_make_flags', please note that RVM can detect number of CPU threads and set the '-j' flag automatically if you do not set it.
grep: write error: Broken pipe
sort: fflush failed: standard output: Broken pipe
sort: write error
Installing Ruby from source to: /home/kings/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
ruby-2.3.0 - #extracting ruby-2.3.0 to /home/kings/.rvm/src/ruby-2.3.0....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
ruby-2.3.0 - #configuring..........................................................
ruby-2.3.0 - #post-configuration..
ruby-2.3.0 - #compiling....................................
ruby-2.3.0 - #installing......
Error running '__rvm_make install',
showing last 15 lines of /home/kings/.rvm/log/1463338801_ruby-2.3.0/install.log
make[2]: Entering directory `/home/kings/.rvm/src/ruby-2.3.0/ext/io/nonblock'
rm -f ../../../.ext/x86_64-linux/io/nonblock.so ../../../.ext/.timestamp/.RUBYARCHDIR.-.io.time
rmdir --ignore-fail-on-non-empty -p ../../../.ext/x86_64-linux/io 2> /dev/null || true
rm -f
rm -f ../../../.ext/x86_64-linux/io/nonblock.so  *.o  *.bak mkmf.log .*.time
rm -f Makefile extconf.h conftest.* mkmf.log
rm -f core ruby *~
rmdir --ignore-fail-on-non-empty -p  2> /dev/null || true
make[2]: Leaving directory `/home/kings/.rvm/src/ruby-2.3.0/ext/io/nonblock'
make[1]: Leaving directory `/home/kings/.rvm/src/ruby-2.3.0'
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
./ruby is not found.
Try `make' first, then `make test', please.
make: *** [do-install-nodoc] Error 1
++ /scripts/functions/support : __rvm_make()  383 > return 2
There has been an error while running make install. Halting the installation.
 ✘ kings@STEPHANLAPTOP  ~ `

**Comment by lateau** [comment]
@natanlim This does not work for me. Some native extensions won't build properly. mkmf generated Makefile causes "missing separator".

```
$ sudo apt-add-repository ppa:brightbox/ruby-ng
$ sudo apt-get update
 sudo apt-get install ruby2.3 ruby2.3-dev
```

**Comment by mike927** [comment]
Has anyone been able to run rails application without any problems already?

**Comment by benhillis** [comment]
I've validated that rvm is working on our internal development build, the `cat: /dev/fd/63: No such file or directory` errors are now also gone now that #266 is fixed.

**Comment by YihongK** [comment]
I got the same error installing Ruby. When the internal build will be released to fast ring?

**Comment by jvilleneuve** [comment]
Anyone in the fast ring have success with the new build?

**Comment by michha** [comment]
Installed todays fast ring build and reinstalled bash:

michael@M:/mnt/c/dev$ curl -L https://get.rvm.io | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    179      0  0:00:01  0:00:01 --:--:--   179
100 22865  100 22865    0     0  17383      0  0:00:01  0:00:01 --:--:--  180k
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
gpg: Signature made Tue 29 Mar 2016 03:49:47 PM DST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/michael/.rvm/archives/rvm-1.27.0.tgz'

Installing RVM to /home/michael/.rvm/
cat: /dev/fd/63: No such file or directory
    Adding rvm PATH line to /home/michael/.profile /home/michael/.mkshrc /home/michael/.bashrc /home/michael/.zshrc.
    Adding rvm loading line to /home/michael/.profile /home/michael/.bash_profile /home/michael/.zlogin.
Installation of RVM in /home/michael/.rvm/ is almost complete:

  * To start using RVM you need to run `source /home/michael/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

<<welcome message removed>>

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io
michael@M:/mnt/c/dev$

**Comment by jvilleneuve** [comment]
@michha if there is a problem, i don't see it. Did it complete successfully?

**Comment by michha** [comment]
@benhillis said that the " cat: /dev/fd/63: No such file or directory" should be gone, but I still see it in my testrun

**Comment by benhillis** [comment]
It Is fixed internally but that fix missed the snap of the most recent Insider build.

**Comment by michha** [comment]
Thanks for the clarification, @benhillis :+1:

**Comment by hut8** [comment]
The update that was installed today seemed to nearly fix it for me. I can compile and install Ruby 2.3 via RVM!

```
liam@DESKTOP-DCPAVOP:~$ rvm install --default 2.3.0
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.0.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating systemliam password required for 'apt-get --quiet --yes update': ..-
.....
Installing required packages: libreadline6-dev, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, sqlite3, autoconf, libgmp-dev, libgdbm-dev, libncurses5-dev, automake, libtool, bison, pkg-config, libffi-devliam password required for 'apt-get --no-install-recommends --yes install libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgmp-dev libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev': ..-
...............
Requirements installation successful.
df: Warning: cannot read table of mounted file systems: No such file or directory
ruby-2.3.0 - #configure
ruby-2.3.0 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25.1M  100 25.1M    0     0  3324k      0  0:00:07  0:00:07 --:--:-- 4346k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.0 - #validate archive
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
The downloaded package for https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.0.tar.bz2,
Does not contains single 'bin/ruby' or 'ruby-2.3.0',
Only '' were found instead.
Mounting remote ruby failed with status 4, trying to compile.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/liam/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.5M  100 13.5M    0     0  3203k      0  0:00:04  0:00:04 --:--:-- 3203k
ruby-2.3.0 - #extracting ruby-2.3.0 to /home/liam/.rvm/src/ruby-2.3.0....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
ruby-2.3.0 - #configuring..........................................................
ruby-2.3.0 - #post-configuration..
ruby-2.3.0 - #compiling.................................................................................
ruby-2.3.0 - #installing...........................
ruby-2.3.0 - #making binaries executable..
Installed rubygems 2.5.1 is newer than 2.4.8 provided with installed ruby, skipping installation, use --force to force installation.
ruby-2.3.0 - #gemset created /home/liam/.rvm/gems/ruby-2.3.0@global
ruby-2.3.0 - #generating global wrappers................
ruby-2.3.0 - #gemset created /home/liam/.rvm/gems/ruby-2.3.0
ruby-2.3.0 - #generating default wrappers..........
ruby-2.3.0 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.3.0 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
```

Then:

```
liam@DESKTOP-DCPAVOP:~$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

Great job!

**Comment by andresclari** [comment]
I managed to install Ruby 2.3.1 as well with out issues, next problem is running Bundler.

RVM Created the gemset properly, I installed bundler. And when trying to run **bundle install** I got the following error:

```
Error details

    ArgumentError: parent directory is world writable but not sticky
      /home/andres/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:93:in `ensure in mktmpdir'
      /home/andres/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:95:in `mktmpdir'

Environment

  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /home/andres/.rvm/gems/ruby-2.3.1@memoryguard
  GEM_PATH  /home/andres/.rvm/gems/ruby-2.3.1@memoryguard:/home/andres/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (master)
  Git       1.9.1

      Bundler settings

  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/andres/.rvm/gems/ruby-2.3.1@memoryguard/bin:/home/andres/.rvm/gems/ruby-2.3.1@global/bin:/home/andres/.rvm/rubies/ruby-2.3.1/bin:/home/andres/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/andres/.rvm/gems/ruby-2.3.1@memoryguard:/home/andres/.rvm/gems/ruby-2.3.1@global"
```

This error happened both running bundler from **/mnt/c/Devel/Projects/project_name** and the same issue copying the project to $HOME and running it from **/home/andres/project_name** so I don't think it is related to using the Windows filesystem vs the Ubuntu.

As a note I'm hoping we can get it to run successfully from the Windows filesystem, since the appeal is to be able to edit your project in Windows, and execute it on Linux.

**Comment by hut8** [comment]
During Bundler running, it creates this directory in ~:

```
drwxrwxrwt 2 liam liam     0 May 28 12:20 .bundle/
```

As you can see, the sticky bit is set. However apparently whatever method Bundler uses to determine if it is set is broken. When I ran `ls` I was also confused to see that most of my files were actually mode 777. This is because somewhere, umask isn't set (try running `umask` in bash). So if you set it to 007, things become less crazy permissions wise.

### Workaround:

```
bash --login # so RVM works
umask 007 # no clue why this is 0 by default; haven't looked into it
rm -rf ~/.bundle
cd ruby-project
bundle
```

Works :100:

**Comment by andresclari** [comment]
@hut8 Thanks!

I can confirm that this workaround works.
Probably the umask mode should be set by default, right?

**Comment by hut8** [comment]
I would put it in your `~/.profile` (that's what I'm doing, actually).

I just figured out why it's not set. I'm not sure how `init` works with WSL, but nothing with `pam` is ever started (the output of `ps aux` is just init, bash, and ps). Ubuntu uses `pam-umask` to set this, which reads `/etc/login.defs` and applies those settings. Nothing related to `pam` is running, so there's the source of the issue.

**Comment by dreyks** [comment]
@hut8 Good findings. You should move this to a separate issue so it wouldn't get lost here

**Comment by hut8** [comment]
Heh, I should have searched first: https://github.com/Microsoft/BashOnWindows/issues/352

**Comment by AbhimanyuAryan** [comment]
how did you install ruby 2.3.1? I have still struck on RVM installation. I have 14342. Do I need to Turn Bash feature OFF and then turn it on and re-install BASH on Windows? I am not sure how do I re-install Bash on Windows

```
cooldudeabhi@ACERASPIRE:~$ rvm install 2.3.1
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.1.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
df: Warning: cannot read table of mounted file systems: No such file or directory
ruby-2.3.1 - #configure
ruby-2.3.1 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 25.1M  100 25.1M    0     0  71285      0  0:06:10  0:06:10 --:--:-- 76063
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #validate archive
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
The downloaded package for https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.3.1.tar.bz2,
Does not contains single 'bin/ruby' or 'ruby-2.3.1',
Only '' were found instead.
Mounting remote ruby failed with status 4, trying to compile.
df: Warning: cannot read table of mounted file systems: No such file or directory
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/cooldudeabhi/.rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  88307      0  0:02:43  0:02:43 --:--:--  129k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #extracting ruby-2.3.1 to /home/cooldudeabhi/.rvm/src/ruby-2.3.1....
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
cat: /dev/fd/63: No such file or directory
ruby-2.3.1 - #configuring..........................................................
ruby-2.3.1 - #post-configuration..
ruby-2.3.1 - #compiling...-
```

**Comment by dreyks** [comment]
There's no fatal error in your log. It's still compiling

The build that succeeded for me was 14352

You can uninstall WSL with `lxrun /uninstall /full`

**Comment by AbhimanyuAryan** [comment]
@dreyks and it is forever compiling and retrying :( 
Same process after failed compilation

**Comment by hut8** [comment]
You never pasted the error that the compile failed with. What does it fail with?

**Comment by AbhimanyuAryan** [comment]
@hut8 wait I'll btw have you got rails running?

**Comment by dreyks** [comment]
I've got Rails running.

**Comment by AbhimanyuAryan** [comment]
It worked for me as well @dreyks....Thanks @hut8

**Comment by AbhimanyuAryan** [comment]
Hey @hut8 @dreyks can you address this issue of 

```
The program 'gem'/'ruby' can be found in the following packages:
 * ruby
 * rubygems
Try: sudo apt-get install <selected package>
```

I have created a question on [Stackoverflow](http://stackoverflow.com/questions/37551636/the-program-gem-can-be-found-in-the-following-packages-windows-bash). Please see the complete error with detail. Thanks

**Comment by dreyks** [comment]
rvm installs ruby into `~/.rvm/` not in `/usr/loca/bin`

what does `echo $PATH` say? It has to mention this folder.

**Comment by AbhimanyuAryan** [comment]
`/home/cooldudeabhi/.rbenv/plugins/ruby-build/bin:/home/cooldudeabhi/.rbenv/shims:/home/cooldudeabhi/.rbenv/bin:/home/cooldudeabhi/.rbenv/shims:/home/cooldudeabhi/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/cooldudeabhi/.rvm/bin`

**Comment by AbhimanyuAryan** [comment]
Yaa its RVM that's maintaining Ruby(forgot that). So what should I mention in .bashrc file? Looks like .bashrc file doesn't include Ruby PATH and that's the reason I see this message. I guess

**Comment by jmoulton** [comment]
Thanks for the update! I have Ruby installed, now having issues with Postgres. Anyone know of an existing issue with `shmmax` not able to be set? I haven't seen much online about it. One day, I'll be able to use my full stack...

**Comment by mikedhart** [comment]
Just to confirm, I got the latest build this morning. I've managed to build both ruby-2.2.2 and ruby-2.3.0. Thanks for the great work!

**Comment by mike927** [comment]
Which build resolves that issue?

**Comment by mikedhart** [comment]
Windows 10 Insider Preview 14352

Although now my only problem is when I run "rails server -b 0.0.0.0" and go to localhost:3000 the browser icon spins but the server does not respond. I will keep looking!

**Comment by mike927** [comment]
> Although now my only problem is when I run "rails server -b 0.0.0.0" and go to localhost:3000 the browser icon spins but the server does not respond. I will keep looking!

simply `rails s` causes the same issue?

**Comment by mikedhart** [comment]
Yep, but I've worked it out now. It seems that thin was the problem. I switched to webrick and the app now runs perfectly. I don't exactly no what the problem was with thin but this solution works for now!

**Comment by YihongK** [comment]
I couldn't get postgres to work. It installed successfully, but when I was trying to connect as the default user, I got the error message "setresuid() [1000,106,1000]->[-1,0-1]: Operation not permitted"

**Comment by Dunkirk** [comment]
I also can't get postgres to work. I guess I'm going to try to install the real Windows version, but my "Services for Linux" is giving me a lot of strange errors with this new release.

> runlevel:/var/run/utmp: No such file or directory

> initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

**Comment by Dunkirk** [comment]
Also, it's about damn time someone made a good terminal for Windows, if this thing finally becomes usable. I've tried all the alternatives, and they're all rubbish.

**Comment by YihongK** [comment]
I found a tutorial on gorails.com.
https://gorails.com/setup/windows/10
They also mentioned "Postgresql installation currently fails on creating the default cluster. could not create shared memory segment: Function not implemented"
We currently don't have any fixes for this, so we recommend using MySQL for now."

We may have to wait a few more builds to get everything work smoothly.

**Comment by andresclari** [comment]
I would suggest using the Windows Postgres version, it works wonderfully in conjunction. No more VirtualBox for me :D

**Comment by dreyks** [comment]
Ok, so 14361 just rocks. rvm installs ruby 2.3.1 from a ready binary without a need to compile. I think we can safely close this one, and maybe make an aggregate issue on Ruby/Rails/gems?

**Comment by Austin-Qu** [comment]
@dreyks Glad to hear this

**Comment by russalex** [comment]
Closing this one and having specific issues on Rails / Gems / Etc... would be useful for us. If the original poster does not close by next week I will do so (planning on doing that with everything tagged as fixed).

I do see there is a new issue #451 which discusses issues executing rails.
