### ISSUE TITLE
file created on window side are not seen in Linux side

### ISSUE THREAD

**Issue by fdu123** [Microsoft/BashOnWindows#45]
Create a file with Notepad in C:\Users\xxx\AppData\Local\lxss\rootfs\tmp

File created can be displayed in Exporer 
but it doesn't appear in linux
root@localhost:/mx6# cd /tmp
root@localhost:/tmp# ls
root@localhost:/tmp#
... nothing ...

even if I reboot my system
Regards,

**Comment by crutchcorn** [comment]
Have you tried ls -a?

**Comment by fdu123** [comment]
Yes of course
Regards,

**Comment by mphaney** [comment]
While this is an interesting phenomenon, should probably take note of the comment by @bitcrazed on issue #44 , to paraphrase: manipulating the Linux filesystem from Windows may cause issues/corruption and should not be done.

**Comment by bitcrazed** [comment]
This is known and expected - please don't modify the "Linux filesystem" from Windows - here be dragons!

**Comment by cosmicdan** [comment]
This is interesting. Since we can't use Unix style permissions on the Windows mounts, how is one supposed to transfer and share data between the Linux and Windows environments? We're forced to manually cp back and forth from ~ to /mnt/*/?

**Comment by NiclasLindgren** [comment]
You did show on the demo of bash that we have full fidelity of the filesystem between the two subsystems, and now you say it isn't so. It would be great with the guidance on how we are meant to use this. On the demo you mentioned that you can use any editor to edit file under the Linux sub system and was one of the pitches.

**Comment by jdmarch** [comment]
I'm not sure what the issue-handling norms are on this project, but closing an issue without solving it would seem to imply "won't fix", which, in turn, would seem to render the bash-on-windows feature almost pointless. Understood that this is in beta, and that patience is in order. But not on the roadmap? If normal cross-OS file write will always be not only unsupported but potentially destabilizing, then what's the point?

**Comment by sunilmut** [comment]
Interoperability is a big topic and something that we are well aware and conscious about. We understand the frustration here from lack of full interoperability and appreciate all the feedback. For the first beta release, our focus was delivering a strong developer focused scenario. Having said that, we do provide some basic interop today in terms of access to Windows volume through WSL.For the next release, we will be taking all of this feedback into account and try to incorporate in our planning. To help us prioritize for future release, please also provide this feedback through our [User Voice Page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo).

Regarding the topic of destabilizing, while it represents the current affairs, it is not an indication of the future state of the project. Please bear with us while we iterate on the project in its beta phase.

**Comment by jdmarch** [comment]
Thanks, @sunilmut . Happy to be patient in the service of future progress! Could you explain, though, what developer-focused scenario you have in mind with the current capabilities? The primary one that occurs to me is being able to use git properly on a Windows machine, and that seems sketchy at present.

**Comment by sunilmut** [comment]
@jdmarch - [Here](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-is-your-high-priority-feature-set-for-the-windows-10-anniversary-edition-) is what we have focused on for this release. But, let that not limit your WSL playground area and do give us feedback on other areas as well. It is mostly useful for setting expectations.

**Comment by JSMike** [comment]
confirmed that when using mklink /J to create a windows link to the Lxss/rootfs path, files could be updated but newly created files weren't visible in WSL.

**Comment by pavelbulanov** [comment]
For records, adding link to [user voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341279-a-file-created-in-c-users-user-appdata-local-lx) for the issue on this specific topic

**Comment by Manouchehri** [comment]
@bitcrazed Have you considered using UnionFS? https://github.com/rpodgorny/unionfs-fuse

**Comment by Biswa96** [comment]
@cyan101 If you want to destroy/play with WSL, then edit those Linux files in Windows IDE or notepad as usual. And then change the file permission with `chmod 666 *`.

**Comment by bitcrazed** [comment]
@Cyan101 The recommendation as per the blog post covering this issue ([Do not change Linux files using Windows apps and tools](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/)), is to create your project files under `<drive>:\<path>` which is thus reachable from Linux via `/mnt/<drive>/<path>`, e.g. `c:\dev\project1` --> `/mnt/c/dev/project1`.

**Comment by cosmicdan** [comment]
Eh, you guys would all be better off running Linux in Hyper-V (assuming you're on Windows 10 Pro) for now - if you're not interested or able to directly contribute to the WSL project. It's pretty good, much faster than VMWare or VirtualBox since MS added the whole Enhanced Linux Guest stuff :D

**Comment by alonbl** [comment]
Unbelievable!

Even cygwin has done a better job.

I thought I will drop cygwin and msys for our users and replace them with the WSL, but it seems like WSL and Windows have not been integrated properly as other tools.

**Comment by cosmicdan** [comment]
There are work-arounds for this, just set your home folder to a different path and enable metadata on automount. Can't remember the exact steps but if you Google for it you'll find a guide. Sharing files between Linux and Windows works perfectly fine now, similar to using SMB in my experience.

On 9 Mar 2019, Alon Bar-Lev <notifications@github.com> wrote:
>Unbelievable!
>
>Even cygwin has done a better job.
>
>I thought I will drop cygwin and msys for our users and replace them
>with the WSL, but it seems like WSL and Windows have not been
>integrated properly as other tools.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by jdmarch** [comment]
@alonbl worth noting -- 
https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/

> What’s new for WSL in Windows 10 version 1903?
> The next Windows update is coming soon and we’re bringing exciting new updates to WSL with it! These include accessing the Linux file system from Windows,..
>  Accessing Linux files from Windows
> In the past, creating and changing Linux files from Windows resulted in losing files or corrupting data. Making this possible has been a highly requested and long anticipated feature. We’re proud to announce you can now easily access all the files in your Linux distros from Windows.

**Comment by DipanshKhandelwal** [comment]
I cannot access the file now. Is there any way I can delete that file?

**Comment by cosmicdan** [comment]
The original issue is resolved here. I believe if people want this functionality right now they'll have to get in on the slow ring, though.

⁣Get BlueMail for Android ​

**Comment by sanderjo** [comment]
> You can, however, modify files in `/mnt/c` (DrvFs) with impunity.

Ah, that works for me: files created on Windows, are visible via `/mnt/c/`

**Comment by vonamord** [comment]
when I "ls" on "mnt" it shows such background that hides all the directories. any ideas how to fix it?
![image](https://user-images.githubusercontent.com/679956/80213445-d99a8480-8641-11ea-8fb6-7781ffeb4469.png)

**Comment by bitcrazed** [comment]
@vonamord I am guessing your color theme uses a white font on a light background. Try setting a dark theme.

**Comment by jt-github** [comment]
For those who are stumbling on this because it's high up in search results, here's the short version:

- You still cannot access the files directly by touching things via C:\whatever\yourdistro\rootfs
- You _can_, however, access the root directory via \\wsl$

Refer to the comment from @jdmarch for a link to all the details.

**Comment by Cloudmersive** [comment]
I can't believe this is not getting fixed.  The whole point of WSL is that you can modify the linux file system from Windows!

**Comment by cosmicdan** [comment]
> I can't believe this is not getting fixed. The whole point of WSL is that you can modify the linux file system from Windows!

But it has been fixed, read previous comments. I had personally enabled automount and metadata of C drive, but this will add some minor IO overhead I imagine (nothing serious for an SSD, surely).

**Comment by therealkenc** [comment]
> But it has been fixed

It had, but note as of this writing #4064 ([message](https://github.com/microsoft/WSL/issues/4064#issuecomment-499960521)) is open.
