### ISSUE TITLE
network issue, not able to ping.

### ISSUE THREAD

**Issue by DrkCoater** [Microsoft/BashOnWindows#469]
Hi, I've installed the latest preview release Build 14342.rs1_release.160506. I'm not able to ping or ap-get install anything from the Internet in BashOnWindows, however I can ping from outside cmd prompt. Thanks.

**Comment by aseering** [comment]
Hi @DrkCoater, thanks for reporting this!  Actually, release 14342 is not the latest release.  Could you try with 14352?  You should be offered it via Windows Update within 24-48 hours after installing if you've put this machine in the Fast Ring.

ping support was first added in 14352, and even in that release it requires Bash to be run with admin privileges to receive ICMP packets.

apt-get should work in older releases and without admin privileges, though it'd be good to confirm that there isn't some relevant bug that was fixed in the latest release.

**Comment by StfBauer** [comment]
Hi @aseering,

I'm currently on the latest build and ping doesn't work there too. I get the error:

```ping: icmp open socket: Permission denied```

Bash is currently running as root.

**Comment by russalex** [comment]
@aseering is correct that Ping will only work in 14352 if you run Bash from an Admin command prompt.  This is independent if you run as root within Bash or not.

There should be no issues with apt-get from a non-elevated command prompt.  There are some basic network troubleshooting steps in #5.  We have seen some issues where users with various 3rd party firewalls are having issues.

**Comment by DrkCoater** [comment]
Thanks, I just upgraded to Build 14361.rs1_release.160603-1700
still the same issue. When ping www.microsoft.com, it took a very long time the come back with unknown host. Do I need to reinstall bashonwindows? If so what's the instruction to reinstall?

**Comment by DrkCoater** [comment]
the /etc/resolv.conf looks fine to me btw. it got the correct name server..

**Comment by russalex** [comment]
@DrkCoater, can you confirm if you are able to ping an IP address?  That is, do you get different behavior between `ping www.microsoft.com` and `ping 23.209.11.168` (on an Admin console naturally).

Starting to see a few reports of errors with DNS lookups.  Checking if you are hitting the same thing.  If so, no resolution yet.

Since you asked, the command to delete the Ubuntu binaries is `lxrun /uninstall`.  More information along with additional options for lxrun [here](https://msdn.microsoft.com/en-us/commandline/wsl/reference).  If that does not work for you, manual instructions [here](https://msdn.microsoft.com/en-us/commandline/wsl/faq#how-do-i-fully-uninstall-wsl-).

**Comment by DrkCoater** [comment]
I just did a successful full reinstall of bash, didn't fix the problem.
I got unknown host when a ping www.microsoft.com after a long pause.
and I get this when ping the ip instead:

PING 23.209.11.168 (23.209.11.168) 56(84) bytes of data.
ping: sendmsg: Invalid argument
ping: sendmsg: Invalid argument
ping: sendmsg: Invalid argument
ping: sendmsg: Invalid argument
...

**Comment by yodurr** [comment]
I have the same DNS issue, ping to an IP works but ping www.microsoft.com does not, says "Unknown host".

**Comment by DrkCoater** [comment]
I've uninstalled avg Internet security and updated the latest insider preview today and Internet access now worked.
