### ISSUE TITLE
Neighboring hostnames known to Windows are not known to WSL

### ISSUE THREAD

**Issue by da2x** [Microsoft/BashOnWindows#605]
In Command Prompt I can run `ping laptop` and get a response from my laptop using it’s unqualified hostname “laptop”. Under WSL, I get the error `unknown host laptop`. I can get to my laptop using it’s fully qualified domain name from DNS, but not using it’s search domain, mDNS name (.local),  hostname, or other nearby-machine discovery. This is very inconvenient.

**Comment by jackchammons** [comment]
Adding your laptop to /etc/hosts would give you the desired effect.

**Comment by benhillis** [comment]
@Aeyoun - if you do "sudo rm /etc/hosts" we will automatically regenerate one with your machine's hostname the next time you launch bash.

**Comment by Aeyoun** [comment]
This has nothing to do with either hosts files.

The _desired effect_ is working local network client discovery using NBNS and NBNS or mDNS so I can reach other clients on my network the same way I can from Command Prompt and PowerShell (plus bash on Linux or Mac).

**Comment by russalex** [comment]
Thanks @Aeyoun.

Some of the confusion here is that on our internal network your scenario appears to be working.  This just makes it slightly harder to track down.

Any chance you can either post or send me an strace of a failing command? Hopefully that will help us track it down.

**Comment by Aeyoun** [comment]
`strace ping hippaforalkus
strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
execve("/bin/ping", ["ping", "hippaforalkus"], [/* 15 vars */]) = -1 EPERM (Operation not permitted)
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted
) = 38
exit_group(1)                           = ?
+++ exited with 1 +++`

`strace ping microsoft.com` gives the same error, yet `ping microsoft.com` actually works.


SSH is probably more interesting:
ssh -p ## d@hippaforalkus
https://gist.github.com/Aeyoun/b317c35247d2800c0611a66a1d917233


ping hippaforalkus, and mounting smb from \\hippaforalkus works in Windows on the same machine, and from other Linux and Macs on the same network. WSL seem to only work with domains that are returned from DNS.

**Comment by aseering** [comment]
WSL doesn't yet support mDNS (as far as I know).  This is covered by #384 .

I'm not really familiar with NBNS under Linux, but I would kind of expect it to fail for similar reasons.

@russalex -- I would expect Dynamic DNS to work, and I would expect Microsoft's network to be using it.  Could that be what's confounding your tests?

**Comment by russalex** [comment]
Thanks @aseering, I did not see #384.  I have confirmed that mDNS and the dbus dependency called out are on our backlog.

As for my testing, I am not certain how MSFT has set up their corporate network, but I would not be surprised if it was Dynamic DNS.

**Comment by MadLittleMods** [comment]
Related to

 - https://github.com/Microsoft/BashOnWindows/issues/149
 - https://github.com/Microsoft/BashOnWindows/issues/731

**Comment by Aeyoun** [comment]
No, @MadLittleMods. Those issues are entirely unrelated.

**Comment by Aeyoun** [comment]
Here is a strace of the `mdns-scan` debug utility:
https://gist.github.com/Aeyoun/87acc829c6e83f9f3cf00719b72fb862

**Comment by cheshrkat** [comment]
FWIW I got the same result trying to ssh into a raspberry pi on my network - can ping host, qualified host and IP from cmd and cygwin (and osx terminal); but can only ping and ssh to the IP address in WSL.

**Comment by rodrymbo** [comment]
@cheshrkat  - While it doesn't solve the underlying problem, adding your local hostnames to `/etc/hosts` does let you connect to them by name until mdns or wins are working.

**Comment by cheshrkat** [comment]
@rodrymbo thanks for the workaround.

**Comment by nimish** [comment]
@rodrymbo sure but that completely defeats the point of using mDNS and it isn't updated dynamically if for example the ipv6 address changes via PE rotation. WSL doesn't support mDNS but Windows 10 does, so this is pretty weird. DNS-SD is much more than just mapping ip addresses to names, there's a whole service discovery bit for things that makes it a lot more convenient.

**Comment by rodrymbo** [comment]
@nimish - Well, workarounds are like that. They let you work for a while until the bigger problem can be fixed. We already know what the bigger problem is; the question is how can we test other parts of the system while that problem gets resolved.

From my perspective, it looks like WSL is passing all networking off to Windows ... except DNS, which the applications running in WSL get from whatever ends up in `/etc/resolv.conf` or whatever. In order to get things working properly, I'd expect one way to get all of the networking going through Windows is to fix the Windows resolver functionality so it can act as a resolver for WSL, on localhost. That would incorporate all the neat tricks (and legacy workarounds) that Windows knows about, and in real time. Or maybe the Devs are going to implement a full network stack of some sort. Who knows. All that's clear is that WSL DNS is handled separately now from the networking, which causes all sorts of problems with LAN and VPN and other kinds of work we want to do. (Or maybe someone can write a Windows app that pretends to be a resolver, passing results back to WSL when - and only when - something in WSL makes the request.)

This area is where we are supposed to report bugs. It turns out this is a feature or backlog or something, the Devs know about  it, nobody likes that it is broken. To express an opinion about what its priority should be, go to the [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash?query=mdns) area. 

To get some work done while we are waiting, add the names to `/etc/hosts` and work away. Or maybe stick with Cygwin or a VM. If you know of a better workaround for while we wait for an official resolution (!), I for one would look forward to learning about it. I'm always up for a good workaround.

**Comment by nimish** [comment]
The workaround doesn't actually work for me since DHCP tends to mess with the ip assignments ;) 

In any case #384 is caused by #376, so until then I'll just switch to using putty or something.

**Comment by rodrymbo** [comment]
@nimish -- Sorry to hear that you have no control over the DHCP server in your testing environment, and its lease times are set so short that assigned IPv4 addresses change so many times a day. :-p But I agree, it will be good to have socket and dbus support added to WSL.

**Comment by sunilmut** [comment]
@da2x - Apologize for the delay in responding to this thread and thanks for the feedback! Is this related to #384, i.e essentially avahi-daemon (the popular mDNS implementation on Ubuntu) does not work in WSL? I tried starting the `avahi-daemon` on WSL and it failed to start. I can see it failing on few socket options such as `SO_REUSEPORT`, `IP_PKTINFO`, `IPV6_MULTICAST_HOPS` and `IPV6_UNICAST_HOPS`.

**Comment by nimish** [comment]
@sunilmut Yes if avahi-daemon works that would be a big step as its the key component that's failing

**Comment by Scandalon** [comment]
This seems to be resolved as of Creators Update. (Ubuntu 16.04.2 LTS) I don't know if it's directly related, but avahi-daemon installs and runs without complaint, as well.

**Comment by sunilmut** [comment]
fyi, see the [update](https://github.com/Microsoft/BashOnWindows/issues/384#issuecomment-320132942)

**Comment by sunilmut** [comment]
Marking this dupe of #384.

**Comment by sunilmut** [comment]
This should be fixed in insider build [16273](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16273)

**Comment by sunilmut** [comment]
I am marking this issue closed. If it persists after upgrading to 16273, please let us know and we can reopen it.

**Comment by ironfroggy** [comment]
I continue to have this issue as of 17134

**Comment by bltavares** [comment]
I still have this issue as well. Looking at the logs, this seems to be related to th `IP_ADD_MEMBERSHIP` errors that were also reported on this issue: https://github.com/Microsoft/WSL/issues/3365
