### ISSUE TITLE
Mongo console is reporting errors under WindowsBash

### ISSUE THREAD

**Issue by alanosman** [Microsoft/BashOnWindows#872]
I managed to get Mongo installed.  I noticed that when the console is running as mongod, errors are being periodically thrown even when there is no activity to mongo.

Example of output errors:

```
2016-08-11T16:52:05.692-0400 I CONTROL  [conn3] mincore failed: errno:38 Function not implemented
2016-08-11T16:52:05.692-0400 I CONTROL  [conn3] mincore failed: errno:38 Function not implemented
2016-08-11T16:52:05.692-0400 I CONTROL  [conn3] mincore failed: errno:38 Function not implemented
2016-08-11T16:53:24.532-0400 I NETWORK  [conn4] end connection 127.0.0.1:62830 (2 connections now open)
2016-08-11T16:53:24.532-0400 I NETWORK  [conn3] end connection 127.0.0.1:62828 (2 connections now open)
2016-08-11T16:53:24.532-0400 I NETWORK  [conn5] end connection 127.0.0.1:62832 (2 connections now open)
2016-08-11T17:19:23.437-0400 I CONTROL  [TTLMonitor] mincore failed: errno:38 Function not implemented
2016-08-11T17:19:23.437-0400 I CONTROL  [TTLMonitor] mincore failed: errno:38 Function not implemented
2016-08-11T17:19:23.437-0400 I CONTROL  [TTLMonitor] mincore failed: errno:38 Function not implemented
```

I'm running this on Windows 10 Build 1607 / 14393.51

I don't know if this is a problem you guys have seen or if this is new.  I was trying to research it, but I could not find anything specific that was a match.

**Comment by acezard** [comment]
Are you using mongodb v 2.4.9 ? I couldn't make the latest version work (3.2.9). I have the same messages as you with that old version

**Comment by alanosman** [comment]
@acezard I am using 3.0.12 if that helps.  It actually all still works, but I see these errors consistently.  I have not migrated development over to WSL yet and am hoping that the Phase 2 release fixes this.

**Comment by sunilmut** [comment]
@alanosman Do you have a strace ("strace -o \<strace_file> -ff \<command>") when these messages are getting logged to the console? It would be helpful to know what it's complaining about.

**Comment by sweetim** [comment]
I have the same problem, I am using Mongo v2.6.12, this happens when I am inserting document

**Comment by roz0n** [comment]
Did anyone ever find a solution for this?

**Comment by sunilmut** [comment]
@sweetim & @roz0n - Can you please share the strace, as per my instructions above? Also, which windows build are you running? You can find that out using the Windows `ver` command. Lastly, do also share the detailed repro steps.

**Comment by sweetim** [comment]
@sunilmut  I am using `Microsoft Windows [Version 10.0.14393]` 
to reproduce it is just by continuously inserting document

```
for (var i = 0; i <1e6; i++) {
    db.test.insert({
         "name": "hello"
    })
}
```

I am sorry, I dont really know how to use that `strace`, but doing the command above i will see the error on my console..

**Comment by aseering** [comment]
@sweetim , just curious, how long does the loop above have to run before you start seeing errors?

I am on the latest [Insider build](http://insider.windows.com/) (build 15046 -- looks like you're using regular stable Windows at build 14393; a lot of networking issues have been fixed in more-recent builds) and I've been running your loop for a few minutes now without seeing any errors.

If I may elaborate a bit on @sunilmut 's strace instructions:  You want to run, at the bash command prompt, `strace -o <strace_file> -ff <command>`.  So, for a MongoDB client, you might for example do something like `strace -o /tmp/strace.txt -ff mongo --host your.mongo.server --port 12345 --ssl`, or whatever arguments (if any) you have to pass to `mongo` to connect and wherever you want to put the strace.txt output.

**Comment by aseering** [comment]
Also, @sweetim , are you connecting to:

* a local Linux MongoDB instance running in WSL?,
* a local Windows MongoDB instance?, or
* a MongoDB server running on a different computer?

**Comment by sweetim** [comment]
@aseering , the moment i run the insert command at `mongo` shell, I could start to see those errors

I have attached the `strace` files here

[strace.zip](https://github.com/Microsoft/BashOnWindows/files/816990/strace.zip)

and I am using a local Linux MongoDB instance running in WSL

**Comment by alanosman** [comment]
Hi @aseering I am back.. sorry for disappearing .. got busy with other projects.

I am going through an effort to ditch cygwin in favor for WSL Ubuntu.  I got back to the point I was at before with this particular issue.  I have WSL running on Windows Creators release.  All is wonderful except for running mongo.

When I start mongod service I am still seeing the minicore failed error.  If you want me to send you some more details, or you have some other suggestions, let me know. I can turn up verbosity on logs or something. 

```
2017-04-20T19:33:52.008-0400 I CONTROL  [TTLMonitor] mincore failed: errno:38 Function not implemented
2017-04-20T19:33:52.008-0400 I CONTROL  [TTLMonitor] mincore failed: errno:38 Function not implemented
2017-04-20T19:33:52.009-0400 I CONTROL  [TTLMonitor] mincore failed: errno:38 Function not implemented
```

The weird thing is that mongo seems to work - I think.  Though I haven't done anything exhaustive yet.

**Comment by aseering** [comment]
Hi @alanosman -- so, there are definitely still issues with services, but in principle you definitely ought to be able to get them to work.

Are you able to simply run the `mongod` command directly (and does that get you a working MongoDB server)?

For what it's worth, I need a MongoDB instance that's always running, and I need to be able to connect to it from Linux, but I don't need to be able to start/stop/etc the server automatically (I just leave it running).  The way I've achieved that is, I downloaded and installed the Windows version of MongoDB.  WSL automatically detects and uses it; no configuration required.  Not the most intellectually satisfying solutions, but it works :-)

**Comment by alanosman** [comment]
Hey Adam @aseering - 

Thanks for the quick response.  So yesterday evening I spend a lot of time tinkering and trying various things out that I am familiar with on regular Ubuntu 14 servers.   

I ended up removing the version of Mongodb I had (which was 3.2x) that I had installed about 4 months ago when I last spent time on WSL and installed 3.4.4 instead.  This actually works now and I do not see the minicore error anymore. Yippy.

So two issues remain.
1. I cannot start it, unless I am root.  I think that just be my configuration and need to spend time looking at privs
2. I cannot start it as a service.  I would just like it to kick off when I start up bash.  I can live without it for sure for now.

Other than that, I think these issues have gone away with 3.4.4. and we can close this.

**Comment by aseering** [comment]
Cool, I'm glad you got this working!

Yeah, WSL does not currently automatically run init scripts.  If you want something to start automatically, you can launch it from your .bashrc file.  Though, that file is run every time you open a new window, so you'll have to handle the case where the process has already been started.

**Comment by alanosman** [comment]
I think we can close this issue now.  Problem has gone away.
